apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world
spec:
  replicas: 2
  selector:
    name: hello-world
  template:
    metadata:
      labels:
        name: hello-world
      name: hello-world
    spec:
      containers:
      - imagePullPolicy: Always
        image: dockercloud/hello-world
        name: hello-world
        # Checks when the container is ready.
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 3
        # Checks if the container is still alive.
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
        ports:
        - containerPort: 80
