apiVersion: v1
kind: ReplicationController
metadata:
  name: server-minefield
spec:
  replicas: 2
  selector:
    name: server-minefield
  template:
    metadata:
      labels:
        name: server-minefield
      name: server-minefield
    spec:
      containers:
      - imagePullPolicy: Always
        image: eu.gcr.io/test-cg/server-minefield:test0
        name: server-minefield
        # Checks when the container is ready.
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 3
        # Checks if the container is still alive.
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080